model:
  name: 'Galerkin_Transformer'
  in_dim: 1
  out_dim: 1
  ref: 8
  # n_hidden: 256
  n_hidden: 96
  n_layers: 6
  n_heads: 8
  dropout: 0.0
  mlp_ratio: 4
  act: 'gelu'
  upsample_factor: [2, 2]

data:
  name: 'NavierStokes2D'
  data_path: "/home/yc/CVPR26/DiffSR/NavierStokes_V1e-5_N1200_T20.mat"
  sample_factor: 2
  shape: [64, 64]
  train_batchsize: 256
  eval_batchsize: 256
  train_ratio: 0.98
  valid_ratio: 0.01
  test_ratio: 0.01
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 2
  epochs: 500
  patience: 10
  eval_freq: 5
  saving_best: True
  load_ckpt: False
  saving_ckpt: True
  ckpt_freq: 5
  ckpt_max: 5
  distribute: False
  distribute_mode: 'DDP'
  device_ids: [0, 1, 2, 3]

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: '/home/yc/CVPR26/DiffSR/logs/galerikin2d'
  wandb: True
  wandb_project: 'DiffSR-galerikin2d-ns2d'