model:
  name: 'HiNOTE'
  in_channels: 1
  out_channels: 1
  feature_up_ratio: 4
  fourier_up: Corner # Options: "Corner", "Area", "Periodic"
  feature_combine: add  # Options: "add", "cat"
  non_act: GELU  # Options: "ReLU", "LeakyReLU", "ELU", "SELU", "GELU", "RReLU"
  liif_up_method: nearest # Options: "nearest", "bilinear"
  attention_width: 256
  attention_head: 16
  hierarchical_levels: 1
  scale_factor: 4

data:
  name: 'NavierStokes2D'
  data_path: "/home/yc/CVPR26/DiffSR/NavierStokes_V1e-5_N1200_T20.mat"
  sample_factor: 4
  shape: [64, 64]
  train_batchsize: 8
  eval_batchsize: 8
  # train_ratio: 0.98
  # valid_ratio: 0.01
  # test_ratio: 0.01
  train_ratio: 0.2
  valid_ratio: 0.01
  test_ratio: 0.01
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 0
  epochs: 500
  patience: 10
  eval_freq: 5
  saving_best: True
  load_ckpt: False
  saving_ckpt: True
  ckpt_freq: 5
  ckpt_max: 5
  distribute: False
  distribute_mode: 'DDP'
  device_ids: [0, 1, 2, 3]

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: '/home/yc/CVPR26/DiffSR/logs/HiNOTE'
  wandb: True
  wandb_project: 'DiffSR-HiNOTE-ns2d'
