model:
  name: 'SRNO'
  input_channels: 1
  output_channels: 1
  use_coord_input: True
  width: 256
  blocks: 16
  upsample_factor: [2, 2]

  encoder_config:
    n_resblocks: 16
    n_feats: 64
    res_scale: 1.0
    scale: 2
    no_upsampling: True
    input_channels: 1
    output_channels: 64


data:
  name: 'NavierStokes2D'
  data_path: "/home/yc/CVPR26/DiffSR/NavierStokes_V1e-5_N1200_T20.mat"
  sample_factor: 2
  shape: [64, 64]
  train_batchsize: 512
  eval_batchsize: 512
  train_ratio: 0.98
  valid_ratio: 0.01
  test_ratio: 0.01
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 0
  epochs: 500
  patience: 10
  eval_freq: 5
  saving_best: True
  load_ckpt: False
  saving_ckpt: True
  ckpt_freq: 5
  ckpt_max: 5
  distribute: True
  distribute_mode: 'DDP'
  device_ids: [1, 2, 3]

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: '/home/yc/CVPR26/DiffSR/logs/sronet2d'
  wandb: True
  wandb_project: 'DiffSR-SRNO2d-ns2d'