model:
  name: 'UNet2d'
  in_channels: 1
  out_channels: 1
  init_features: 64

data:
  name: 'NavierStokes2D'
  data_path: "/ai/gno/DATA/ns/ns_V1e-5_N1200_T20.mat"
  sample_factor: 4
  shape: [64, 64]
  train_batchsize: 512
  eval_batchsize: 512
  train_ratio: 0.98
  valid_ratio: 0.01
  test_ratio: 0.01
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'
  num_workers: 2

train:
  random_seed: 42
  cuda: True
  device: 0
  epochs: 500
  patience: 10
  eval_freq: 10
  saving_best: True
  load_ckpt: False
  saving_ckpt: True
  ckpt_freq: 50
  ckpt_max: 3
  distribute: False
  distribute_mode: 'DDP'
  device_ids: [0, 1, 2, 3]

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 200
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
