model:
  name: 'FNO2d'
  modes1: [15, 12, 9, 9, 9]
  modes2: [15, 12, 9, 9, 9]
  width: 64
  fc_dim: 128
  layers: [16, 24, 24, 32, 32]
  in_dim: 1
  out_dim: 1
  act: 'gelu'
  pos_dim: 2
  upsample_factor: [4, 4]

data:
  name: 'Ocean'
  data_path: "/data/global_ocean_surface_velocity/ocean_uovo_128_128_1997_subset5000.h5"
  data_key: 'uo_data'
  # data_key: 'vo_data'
  sample_factor: 4
  shape: [128, 128]
  train_batchsize: 256
  eval_batchsize: 256
  train_ratio: 0.98
  valid_ratio: 0.01
  test_ratio: 0.01
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 0
  epochs: 500
  patience: 10
  eval_freq: 5
  saving_best: True
  load_ckpt: False
  saving_ckpt: True
  ckpt_freq: 5
  ckpt_max: 5
  distribute: False
  distribute_mode: 'DDP'
  device_ids: [0, 1, 2, 3]

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: '/home/yc/CVPR26/DiffSR/logs/Ocean/uo_data_FNO2d'
  # log_dir: '/home/yc/CVPR26/DiffSR/logs/Ocean/vo_data_FNO2d'
  wandb: True
  wandb_project: 'DiffSR-FNO2d-Ocean_uo'
  # wandb_project: 'DiffSR-FNO2d-Ocean_vo'
