model:
  model_name: 'DGPO'
  in_dim: 3
  out_dim: 1
  hidden_dim: 32
  pos_dim: 2
  num_layers: 3
  num_heads: 4
  num_gaussians: 128
  # gs_path: '/ai/gno/CODE/GPNO/logs/NavierStokes/05_06/GaussianField_22_44_08' 
  gs_path: '/ai/gno/CODE/GPNO/logs/NavierStokes/05_07/GaussianField_22_35_21' # 8
  # gs_path: '/ai/gno/CODE/GPNO/logs/NavierStokes/05_07/GaussianField_22_10_07' # 1

data:
  dataset: 'NavierStokes2D'
  data_path: "/ai/gno/DATA/ns/ns_V1e-5_N1200_T20.mat"
  sample_factor: 1
  train_batchsize: 32
  eval_batchsize: 32
  in_t: 1
  out_t: 1
  duration_t: 10
  train_ratio: 0.8
  valid_ratio: 0.1
  test_ratio: 0.1
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 2
  epochs: 500
  patience: -1
  eval_freq: 1
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.0001

schedule:
  scheduler: 'StepLR'
  step_size: 400
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
