model:
  name: 'FNO2d'
  modes1: [15, 12, 9, 9, 9]
  modes2: [15, 12, 9, 9, 9]
  width: 64
  fc_dim: 128
  layers: [16, 24, 24, 32, 32]
  in_dim: 1
  out_dim: 1
  act: 'gelu'
  pos_dim: 2
  upsample_factor: [2, 2]

data:
  name: 'NavierStokes2D'
  data_path: "/ai/gno/DATA/ns/ns_V1e-5_N1200_T20.mat"
  sample_factor: 2
  train_batchsize: 128
  eval_batchsize: 128
  train_ratio: 0.98
  valid_ratio: 0.01
  test_ratio: 0.01
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 0
  epochs: 500
  patience: 10
  eval_freq: 5
  saving_best: True
  load_ckpt: False
  saving_ckpt: True
  ckpt_freq: 5
  ckpt_max: 5
  distribute: True
  distribute_mode: 'DDP'
  device_ids: [0, 1, 2, 3]

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
