model:
  model_name: 'GaussianField'
  in_dim: 3
  out_dim: 1
  hidden_dim: 64
  pos_dim: 2
  num_gaussians: 4
  sigma_init: 0.1

data:
  dataset: 'NavierStokes2D'
  data_path: "/ai/gno/DATA/ns/ns_V1e-5_N1200_T20.mat"
  sample_factor: [1, 1]
  train_batchsize: 4
  eval_batchsize: 4
  train_ratio: 0.8
  valid_ratio: 0.1
  test_ratio: 0.1
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 1
  epochs: 1000
  patience: -1
  eval_freq: 1
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
