model:
  name: 'UNet2d'
  in_channels: 1
  out_channels: 1
  init_features: 32

data:
  name: 'NavierStokes2D'
  data_path: "/ai/gno/DATA/ns/ns_V1e-5_N1200_T20.mat"
  sample_factor: 2
  train_batchsize: 1024
  eval_batchsize: 1024
  train_ratio: 0.8
  valid_ratio: 0.1
  test_ratio: 0.1
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'
  num_workers: 2

train:
  random_seed: 42
  cuda: True
  device: 0
  epochs: 20
  patience: 10
  eval_freq: 10
  saving_best: True
  load_ckpt: False
  saving_ckpt: True
  ckpt_freq: 10
  ckpt_max: 5
  distribute: False
  distribute_mode: 'DP'
  device_ids: [0, 1, 2, 3]

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
